[project]
# Whether to enable telemetry (default: true). No personal data is collected.
enable_telemetry = true

# List of environment variables to be provided by each user to use the app.
user_env = []

# Duration (in seconds) during which the session is saved when the connection is lost
session_timeout = 3600

# Enable third parties caching (e.g LangChain cache)
cache = false

# Follow symlink for asset mount (see https://github.com/Chainlit/chainlit/issues/317)
# follow_symlink = false

[features]
# Show the prompt playground
prompt_playground = true

# Process and display HTML in messages. This can be a security risk (see https://stackoverflow.com/questions/19603097/why-is-it-dangerous-to-render-user-generated-html-or-javascript)
unsafe_allow_html = false

# Process and display mathematical expressions. This can clash with "$" characters in messages.
latex = false

# Authorize users to upload files with messages
multi_modal = true

# Allows user to use speech to text
[features.speech_to_text]
    enabled = false
    # See all languages here https://github.com/JamesBrill/react-speech-recognition/blob/HEAD/docs/API.md#language-string
    # language = "en-US"

[UI]
# Name of the app and chatbot.
name = "Qubert"

# Show the readme while the conversation is empty.
show_readme_as_default = true

# Description of the app and chatbot. This is used for HTML tags.
# description = ""

# Large size content are by default collapsed for a cleaner ui
default_collapse_content = true

# The default value for the expand messages settings.
default_expand_messages = false

# Hide the chain of thought details from the user in the UI.
hide_cot = false

# Link to your github repo. This will add a github button in the UI's header.
# github = ""

# Specify a CSS file that can be used to customize the user interface.
# The CSS file can be served from the public directory or via an external link.
# custom_css = "/public/test.css"
# Override default MUI light theme. (Check theme.ts)
[UI.theme.light]
background = "#FAFAFA"  # Light grey for a neutral background
paper = "#FFFFFF"       # White for elements like cards and sheets

[UI.theme.light.primary]
main = "#F47C30"    # Vibrant orange, reminiscent of Q*bert's color
dark = "#FF4500"    # A very very dark orange color
light = "#FFA04A"   # A very very light orange

[UI.theme.light.secondary]
main = "#5C3FBF"    # Deep purple for a contrasting accent
dark = "#422C90"    # A darker shade of the secondary color
light = "#7B6FD6"   # A lighter, more pastel purple

[UI.theme.light.highlight]
main = "#FFD700"    # Golden yellow for highlights and energy

# Override default MUI dark theme. (Check theme.ts)
[UI.theme.dark]
background = "#1A1A1A"  # Dark grey, simulating the arcade screen
paper = "#242424"       # Slightly lighter grey for contrast

[UI.theme.dark.primary]
main = "#F47C30"    # Keeping the vibrant orange for consistency
dark = "#C35D15"    # Same dark shade for depth
light = "#FFA04A"   # Light orange for a pop of color

[UI.theme.dark.secondary]
main = "#5C3FBF"    # Deep purple to maintain contrast in the dark theme
dark = "#422C90"    # A darker shade for depth
light = "#7B6FD6"   # Light purple for subtlety

[UI.theme.dark.highlight]
main = "#FFD700"    # Golden yellow for a striking pop

[meta]
generated_by = "0.7.700"
